apiVersion: v1
# apiVersion is for creating different kinds object you cn create given a config file
# There are 4 types of components(objects) in K8S: 
# 1. StatefulSet, 2. ReplicaContoller, 3. Pod, 4. Service 
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
  # any name of the container, this is useful to let other containers in K8S to connect
  - name: client
    image: stephengrider/multi-worker
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    # expose port in the node in that container but this is not enough for you to access this container
      - containerPort: 3000
