kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{ .Values.app }}
              servicePort: {{ .Values.service_port }}
            path: "/"
            pathType: Prefix
      host: {{ .Values.app }}.aad.{{ .Values.environment }}.com
