kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app }}
  ports:
    - name: api-endpoint
      protocol: TCP
      port: {{ .Values.service_port }}
      targetPort: {{ .Values.app_port }}