apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
# ClusterIP only port and target port since it is unreachable from the ourside
  type: ClusterIP
  selector:
    component: postgres
  ports:
  # outide want ti reach
  - port: 5432
    targetPort: 5432
  # target port is the one reaching the service
