apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
# ClusterIP only port and target port since it is unreachable from the ourside
  type: ClusterIP
  selector:
    component: server
  ports:
  # outide want ti reach
  - port: 5000
    targetPort: 5000
  # target port is the one reaching the service