apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 2Gi
  # this is to tell K8S to find a storage instance for this accessmode with 2 Gi storage
  accessModes:
    - ReadWriteOnce
