apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # replicas: 1
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
           claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            # the data will be store in this path in the folder called "postgres" (subpath)
            - mountPath: /var/lib/postgressql/data
              subPath: postgres
              name: postgres-storage
              # go back to the above and ask K8S for the storage
